# Generated by Django 2.2.2 on 2019-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
