# Generated by Django 2.2.4 on 2019-08-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_webproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
