# Generated by Django 5.0.1 on 2024-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_enclosure_description_enclosure_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='guid',
            field=models.CharField(blank=True, db_index=True, max_length=768, null=True),
        ),
    ]
