# Generated by Django 4.2.3 on 2024-02-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_source_last_read_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebProxy',
        ),
        migrations.AddField(
            model_name='enclosure',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
