# Generated by Django 5.0.3 on 2024-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_post_json_source_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='alt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
