# Generated by Django 4.2.29 on 2026-03-21 08:55

from django.db import migrations, models

import feeds.models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0015_source_alt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="due_poll",
            field=models.DateTimeField(default=feeds.models.default_due_poll),
        ),
    ]
