# Generated by Django 4.2.29 on 2026-03-21 09:14

from django.db import migrations, models

from ._idempotent_operations import AddConstraintIfMissing
from ._legacy_duplicate_preflight import preflight_legacy_duplicates


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0016_source_due_poll_timezone_aware_default"),
    ]

    operations = [
        migrations.RunPython(
            preflight_legacy_duplicates,
            migrations.RunPython.noop,
        ),
        AddConstraintIfMissing(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guid__isnull", False)),
                fields=("source", "guid"),
                name="feeds_post_unique_source_guid_when_guid_present",
            ),
        ),
        AddConstraintIfMissing(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("feed_url",), name="feeds_source_unique_feed_url"
            ),
        ),
        AddConstraintIfMissing(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source__isnull", False)),
                fields=("user", "source"),
                name="feeds_subscription_unique_user_source_when_source_present",
            ),
        ),
    ]
